### ISSUE TITLE
add proxy

### ISSUE THREAD

**Issue by MuoiTom** [XternA/income-generator#20]
I don't know how to add a proxy to the tool. please guide me

**Comment by XternA** [comment]
I'd like to know why you want to run it via a proxy? What are you trying to achieve and what is your setup?

The reason for no proxy support is stated here: https://github.com/XternA/income-generator/wiki/FAQ#why-you-dont-support-proxies.

Using a proxy will subject your breach against the T&Cs of these applications.

This isn't something I haven't not considered. It's on my list and can be added anytime but until I'm certain that it won't cause any problems, unfortunately it won't be added for the meantime. It is a feature option I am closely monitoring at. When the time is right, I'll probably integrate it across the tool.

**Comment by MuoiTom** [comment]
Thank a lot

**Comment by XternA** [comment]
No worries. Rest assure that when the time is right I will integrate it as I will personally be using it.
