### ISSUE TITLE
peer2profit: how do we get the device_id ?

### ISSUE THREAD

**Issue by lalejand** [XternA/income-generator#34]
The config wizard asks for a peer2profit device id. I don't what to put.

**Comment by XternA** [comment]
I don't exactly remember it needing one, so I'd say just put your host machine's name as a reference for now. 

I'll have to look back at the code changes if anything and update it. Overall, it shouldn't affect you so just put something recognisable in case it's used to identify the node.

**Comment by XternA** [comment]
Parameter has been removed.
