### ISSUE TITLE
Release RAM restriction

### ISSUE THREAD

**Issue by TheHolyStone** [XternA/income-generator#37]
In my server, I actually don't need that much RAM to run my own programs. I hope Igm can use more RAM during runtime. Can an option be added to allow Igm's resource usage to be unrestricted?

**Comment by XternA** [comment]
Even if your own programs doesn't use that much RAM, it's still better to not let IGM run unrestricted. Although personally applications within IGM doesn't consume that much RAM, and practically zero for the tool itself, generally it's a good practice to allow the system to have sufficient capacity for other operations.

If you really want to run the apps with more RAM, then you can set the resource limit to `MAX` this would give it 75% of the host's maximum RAM capacity to use. Do note that this means each application can use up to 75% of your total RAM and not collectively.

It is possible to add an option for allowing maximum resource usage, but it might someday cause the host system to hang in the event of `out of memory` or as more applications gets added and RAM usage overall increases.

Hope this answers the decision behind it.

**Comment by TheHolyStone** [comment]
In my actual use of Igm, I found that nodepay and grass suddenly consume a large amount of CPU and RAM at certain times. I am not sure if this will affect other programs in Igm, so I raised this question. Thank you very much for your answer.

**Comment by XternA** [comment]
Yeah, those apps run a browser within the container as those apps basically run off a browser extension, hence the sudden spike in usage once in a while.  It won't affect other applications as they're all isolated. They all share the host's resources but will be constrained to their own.
