### ISSUE TITLE
containers and proxies

### ISSUE THREAD

**Issue by mrphuong186** [XternA/income-generator#40]
can run multiple containers in ubutu VM?
can add 1 proxy per container?
i cant find where to add proxy.
thanks a lot

**Comment by XternA** [comment]
Hi Phương, I'll keep it simple for you.

1.Proxy support is coming soon. Actually I'm in the final stage of testing it before releasing so stay tuned in the next couple of days, subject to how busy I might be.
2. It makes no sense to run multiple containers of the same IP within the same host.
3. Once proxy feature is out, it basically answers point 1, You'll be able to easily scale multiple instances using proxy which will deploy based on how many IP addresses you have.

Hope that answers your question.

**Comment by mrphuong186** [comment]
awesome
i really like your code layout, it works great, you are awesome.
i can't find where to add new project to active list?
did you design it?
thanks a lot.

**Comment by mrphuong186** [comment]
> Hi Phương, I'll keep it simple for you.
> 
> 1. Proxy support is coming soon. Actually I'm in the final stage of testing it before releasing so stay tuned in the next couple of days, subject to how busy I might be.
> 2. It makes no sense to run multiple containers of the same IP within the same host.
> 3. Once proxy feature is out, it basically answers point 1, You'll be able to easily scale multiple instances using proxy which will deploy based on how many IP addresses you have.
> 
> Hope that answers your question.
> 
> For now just install as usual, and refer to the [wiki guide](https://github.com/XternA/income-generator/wiki) for troubleshooting and useful information.

can't wait
when do you estimate the new version will be updated?
i am looking forward to your new version

**Comment by XternA** [comment]
I'm a bit caught up with other agendas at the moment so I don't want to keep your hopes up but it shouldn't be too long.

Technically the first iteration is complete and actually I can just release it now. But I'm holding back and refining it further before pushing the update. Either way, once I feel it's right, it'll be released. So do keep an eye out or just watch this repo and you'll be notified. 

For now, I wouldn't wait until the version is released. Just go ahead and run the current one and start earning. I want to ensure that once the update is out you can just deploy the proxy instances with zero configuration required and scale up.

I appreciate your patience and continued support once again.

**Comment by XternA** [comment]
Multi-proxy support is now available in IGM under release version [1.11](https://github.com/XternA/income-generator/releases/tag/1.11).

Update the IGM tool to get the latest update with proxy features.

Proxy menu is independent from main IGM. Use `igm proxy` to access proxy menu.

See [multi-proxy support](https://github.com/XternA/income-generator/wiki/Multi%E2%80%90Proxy-Support) guide for detailed information and instructions.
