### ISSUE TITLE
Maybe some adjustments needed in the wiki

### ISSUE THREAD

**Issue by lalejand** [XternA/income-generator#45]
In that page https://github.com/XternA/income-generator/wiki/Windows-Guide, I had to:
- perform wsl.exe --update before doing wsl --install
- perform wsl --install -d Ubuntu instead of wsl --install

**Comment by XternA** [comment]
Really appreciate your efforts providing the improvement and your experience. 

Will definitely, update the wiki page.

Thanks for your effort.

**Comment by XternA** [comment]
Documentation has been updated.
