### ISSUE TITLE
Grass node failure

### ISSUE THREAD

**Issue by TheHolyStone** [XternA/income-generator#46]
Since about a day ago, all grass nodes have been offline and reinstalling them does not work.

**Comment by XternA** [comment]
Did you update tool since then?

Just want to clarify if it's before or after the release of 1.11 nothing was touched on the `Grass node` image.

**Comment by TheHolyStone** [comment]
After the update, I have removed and reinstalled grass, but it still shows as disconnected.

**Comment by XternA** [comment]
Thanks for the confirmation. Could I kindly get a screenshot of the logs for reference please. Thanks again.

**Comment by TheHolyStone** [comment]
I am happy to provide you with information. How can I view the logs?

**Comment by XternA** [comment]
docker logs grass

This should let you view the log for the grass container.

**Comment by TheHolyStone** [comment]
![1729710654(1)](https://github.com/user-attachments/assets/57ac0eea-d836-4d97-ba9a-dbe098f62440)
![1729710563(1)](https://github.com/user-attachments/assets/122557ee-6473-4fdb-bf42-b10ce95def4d)

**Comment by XternA** [comment]
Image is fixed and working now. You should be able to run `Grass` again without issues.

![image](https://github.com/user-attachments/assets/6cdfc1dc-5cc5-47aa-abc6-db747868b218)
