### ISSUE TITLE
multiple accounts

### ISSUE THREAD

**Issue by mrphuong186** [XternA/income-generator#52]
as you know Nodepay and honeygain only allow 10 devices for 1 account, how to run more than 1 account? for example 40 proxies for 4 different accounts?
Thanks a lot

**Comment by XternA** [comment]
Yes I'm well aware of that.

I would **very strongly** urge you not to create multiple accounts, as you will seriously risk getting all of your accounts banned.

However, if you absolutely must ignore my warning and proceed, I won't account for any liability if your account is banned.

You can do the following:

1. Create an new account and you must not refer from your own account.
2. Do not run the application with the different account on the same device or in the same location.
3. Make sure the application with the new account is deployed and ran on a separate device no in the same IP address your own, so you have to run it in another location.

So with all the points and warnings mentioned, you run the tool on another device with another account details and deploy another 10 instances, just for those two applications or with others.

This is the best way I can think of.
