### ISSUE TITLE
Multiple IP hosts

### ISSUE THREAD

**Issue by TheHolyStone** [XternA/income-generator#55]
If my host is routed to multiple IPs, can I use Igm's proxy function to distribute them to containers?

**Comment by XternA** [comment]
Hi, I don't have a use case for running my host via multiple IP routing so I won't be able to test it unfortunately. 

You can try put the IP address and ports pointing to that particular IP entry in the proxy file and see if would work after you deploy the proxy instances.

Verify in the dashboard of the app and see if you see a device registration entry registered with that IP address. `PacketShare` device tab is good example to check if the device can be picked up with the IP address.

![image](https://github.com/user-attachments/assets/bced423b-cf3d-4ae8-9733-05e7d1930d11)

Give that a try. Would be good to know if it works or not. If it doesn't show up the, it probably doesn't work.
