### ISSUE TITLE
Add config issue

### ISSUE THREAD

**Issue by thienha1** [XternA/income-generator#58]
![Capture](https://github.com/user-attachments/assets/601cd56e-ffab-45f6-9305-8c1c3c1be900)
![Capture (1)](https://github.com/user-attachments/assets/e0943c79-b928-42bf-9e02-b63cb191f2c9)
Those UUID always blank after auto-generated...

**Comment by XternA** [comment]
Thanks for pointing this out. I will look into it shortly. I'm currently travelling across the globe so, once I get a bit of time I'll check this issue. Thanks for your patience.

**Comment by XternA** [comment]
Hi, the issue regarding the UUID has been fixed in this PR https://github.com/XternA/income-generator/pull/64.

Please kindly update the tool to the latest version and re-run the setup config to regenerate your UUIDs or reuse if you already have them.
