### ISSUE TITLE
Install App Issue

### ISSUE THREAD

**Issue by thienha1** [XternA/income-generator#59]
![Capture (2)](https://github.com/user-attachments/assets/5017d920-1442-4a11-bac5-70d74fc569fe)
Anything else pull fine except this...error Packetshare

**Comment by XternA** [comment]
I will check if the image is still available. It could be that the image is currently pulled offline hence it can't find the image to download. Just temporarily disable and don't deploy `Packetshare` for now. It won't stop you from being able to run other apps.

**Comment by XternA** [comment]
I got this I think yesterday as I was roaming with different internet. I think it's dues to internet speed and it couldn't talk to the server.

I've tried pulling from another machine and it works so there's nothing wrong with pulling the docker image for `Packetshare`. You may need to just try again but not immediately.

Alternatively you can also check `docker image` to see if the image is already pulled. Alternatively you can verify and try to pull the image manually yourself also with `docker pull packetshare/packetshare:latest`
