### ISSUE TITLE
Glass Node issue

### ISSUE THREAD

**Issue by thienha1** [XternA/income-generator#61]
I download latest version and tried login manually my own in website, work normal but this error, i can't find out where cause this error
![Capture (4)](https://github.com/user-attachments/assets/f9cdd124-8b6e-4fb6-8ba7-606abada6ca7)

**Comment by XternA** [comment]
It's probably due to a new chrome update. Please allow some patience whilst I figure out the cause.

**Comment by XternA** [comment]
For these types of applications that runs a browser internally, which is what this app is doing and the stack usually refers to the browser update change etc.

In most case you can ignore the issue and simply redeploy which generally fixes the issue. Alternative, is to wait for a new update of the application image to be pushed, As long as you have the app running, it will be automatically updated when available and will fix itself.

Just verify in the dashboard that the node is still running.
