### ISSUE TITLE
Traffmonetizer Issue

### ISSUE THREAD

**Issue by thienha1** [XternA/income-generator#63]
![Capture (4)](https://github.com/user-attachments/assets/3935ed04-563a-4464-a230-b141da3aa076)
I tried restart multiple times and still cause too many error...

**Comment by XternA** [comment]
I'm also getting similar issues. This means something has changed recently on their end or related to the communication between the app and their server. 

I'll need to check if there's any changes to the official image or have they moved things.

**Comment by XternA** [comment]
OK in order to fix this one which has worked for me. I've simply redeployed the `traffmonetizer` application and it's working again. This is also true for proxy versions.

To confirm it's working, the only thing you should see from the logs is your token and an ID associated for that app as a device identifier.

<img width="818" alt="image" src="https://github.com/user-attachments/assets/0a6612dd-63e6-4b2f-a0f6-031597580ed7">

**Comment by thienha1** [comment]
> OK in order to fix this one which has worked for me. I've simply redeployed the `traffmonetizer` application and it's working again. This is also true for proxy versions.
> 
> To confirm it's working, the only thing you should see from the logs is your token and an ID associated for that app as a device identifier.
> 
> <img alt="image" width="818" src="https://private-user-images.githubusercontent.com/9136075/393310913-0a6612dd-63e6-4b2f-a0f6-031597580ed7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTMwMzUsIm5iZiI6MTczMzc1MjczNSwicGF0aCI6Ii85MTM2MDc1LzM5MzMxMDkxMy0wYTY2MTJkZC02M2U2LTRiMmYtYTBmNi0wMzE1OTc1ODBlZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMTM1ODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBhZTY4Y2UzOTZiZDBjZWY3NmEwZmYyMDA3NjgxMDMwMWNhYTdjMDcxYWY2MWM4MDY1YWVjNDg5NDAzOTkxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.r_Wvajxg7ZPwC7S4nsxyJw6q5vI7NoLmpNNvZ27vg3Y">

same as u, it working again

**Comment by XternA** [comment]
Thanks for confirming.
