### ISSUE TITLE
Honeygain API error

### ISSUE THREAD

**Issue by d-taborda** [XternA/income-generator#71]
Hello,

For the past few days, Honeygain is not working anymore while using igm. The rest seems to be fine so it is really an issue with Honeygain only.

I keep seeing this error on the docker logs:
![image](https://github.com/user-attachments/assets/35530361-7577-4076-a237-9d27519cf676)

And it is offline on the dashboard:
![image](https://github.com/user-attachments/assets/12c69896-a0d3-41f0-8ee9-3bd9ed112a61)

I have restarted my device and also uninstalled/reinstalled the app, it still continues.

Any idea on what is the problem? Anybody else facing the same issue?

**Comment by XternA** [comment]
Hi there,

Please kindly tell me the OS you're using. I'm assuming you're on Windows?

There's no issue with Honeygain as of speaking. I can confirm that the app is working, even in proxy mode.

So based on the screenshot error, a 4xx HTTP status usually indicates something wrong the user's input. I would suggest go through setup configuration setup again to re-configure the credentials for Honeygain as you mentioned uninstall/reinstall doesn't work, so my theory would be probably your credentials needs re-doing again?

Give that a try and let me know, but as for now, everything is confirmed working.

**Comment by d-taborda** [comment]
Hi,

I'm not on Windows, I'm running an Ubuntu VM, with the following OS:
  Operating System: Ubuntu 24.04.1 LTS
  Kernel: Linux 6.8.0-51-generic
  Architecture: x86-64

igm with docker.

I have not changed my login nor password for Honeygain, it has always been working fine. Only past few days it stopped for unknown reasons. I have tried to update my Honeygain password just now to a new one and update my config file + housekeep docker + remove all apps + install apps again. 
I've done that several times, issue stills persists.
I am not sure what is the problem, nothing changed.

![image](https://github.com/user-attachments/assets/33a379c2-2365-4b73-a4d3-84bd2f5f182b)

**Comment by d-taborda** [comment]
Not an issue on your end, I found the problem. Sorry for bothering you.
